name: Extract URLs

on:
  push:
    branches:
      - main

jobs:
  extract-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch JSON from URL and extract URLs
      run: |
        python - <<EOF
        import requests
        import json

        # URL of the JSON data
        url = 'https://urlhaus.abuse.ch/downloads/json_recent/'  # Replace with the actual URL

        # Fetch the JSON data from the URL
        response = requests.get(url)
        data = response.json()

        # Initialize a list to hold the extracted URLs
        extracted_urls = []

        # Iterate over all entries in the JSON data
        for key, entries in data.items():
            for entry in entries:
                # Extract the "url" field and remove the "http://" part
                extracted_url = entry["url"].replace("http://", "")
                extracted_urls.append(extracted_url)

        # Save the extracted URLs to a .txt file
        with open('new_format.txt', 'w') as file:
            for extracted_url in extracted_urls:
                file.write(extracted_url + '\n')

        # Print the extracted URLs
        for extracted_url in extracted_urls:
            print(extracted_url)
        EOF

    - name: Commit and push the new format file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add new_format.txt
        git commit -m "Add new_format.txt with extracted URLs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.URL_BLOCKLIST_TOKEN }}
